"""init

Revision ID: 94fc52b273d6
Revises: 
Create Date: 2023-01-09 01:33:03.204368

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '94fc52b273d6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('city',
    sa.Column('guid', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.Column('district_id', sa.Integer(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('people', sa.Integer(), nullable=True),
    sa.Column('area', sa.Float(), nullable=True),
    sa.Column('head', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('guid')
    )
    op.create_index(op.f('ix_city_guid'), 'city', ['guid'], unique=False)
    op.create_table('district',
    sa.Column('guid', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('guid')
    )
    op.create_index(op.f('ix_district_guid'), 'district', ['guid'], unique=False)
    op.create_table('last_appeal_date',
    sa.Column('date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('guid', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.PrimaryKeyConstraint('guid')
    )
    op.create_index(op.f('ix_last_appeal_date_guid'), 'last_appeal_date', ['guid'], unique=False)
    op.create_table('region',
    sa.Column('guid', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('guid')
    )
    op.create_index(op.f('ix_region_guid'), 'region', ['guid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_region_guid'), table_name='region')
    op.drop_table('region')
    op.drop_index(op.f('ix_last_appeal_date_guid'), table_name='last_appeal_date')
    op.drop_table('last_appeal_date')
    op.drop_index(op.f('ix_district_guid'), table_name='district')
    op.drop_table('district')
    op.drop_index(op.f('ix_city_guid'), table_name='city')
    op.drop_table('city')
    # ### end Alembic commands ###
