version: "3.4"
services:
  database_filling_submodule:
    container_name: database_filling_submodule
    hostname: database_filling_submodule
    restart: always
    build:
      context: ..
      dockerfile: ./modules/database_filling_submodule/Dockerfile
    networks:
      - global
    env_file:
      - ${ENV_FILE}
  excel_data_module:
    container_name: excel_data_module
    hostname: excel_data_module
    restart: always
    build:
      context: ..
      dockerfile: ./modules/excel_data_module/Dockerfile
    networks:
      - global
    env_file:
      - ${ENV_FILE}
  fias_api_and_wikidata_module:
    container_name: fias_api_and_wikidata_module
    hostname: fias_api_and_wikidata_module
    restart: always
    build:
      context: ..
      dockerfile: ./modules/fias_api_and_wikidata_module/Dockerfile
    networks:
      - global
    env_file:
      - ${ENV_FILE}
  nginx:
    container_name: settlements-rf
    hostname: settlements-rf
    image: nginx
    restart: unless-stopped
    ports:
      - "4110:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - global
    env_file:
      - ${ENV_FILE}
networks:
  global:
    external: true