"""create_auto_distr

Revision ID: 1ca4517f40a5
Revises: fbfcbaaf5ceb
Create Date: 2023-01-09 17:14:20.382904

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision = '1ca4517f40a5'
down_revision = 'fbfcbaaf5ceb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('autonomic_district',
    sa.Column('guid', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('region_guid', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('population', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['population'], ['population.guid'], ),
    sa.ForeignKeyConstraint(['region_guid'], ['region.guid'], ),
    sa.PrimaryKeyConstraint('guid')
    )
    op.create_index(op.f('ix_autonomic_district_guid'), 'autonomic_district', ['guid'], unique=False)
    op.drop_constraint('local_subject_region_guid_fkey', 'local_subject', type_='foreignkey')
    op.create_foreign_key(None, 'local_subject', 'region', ['region_guid'], ['guid'])
    op.drop_constraint('region_district_guid_fkey', 'region', type_='foreignkey')
    op.create_foreign_key(None, 'region', 'federal_district', ['district_guid'], ['guid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'region', type_='foreignkey')
    op.create_foreign_key('region_district_guid_fkey', 'region', 'country', ['district_guid'], ['guid'])
    op.drop_constraint(None, 'local_subject', type_='foreignkey')
    op.create_foreign_key('local_subject_region_guid_fkey', 'local_subject', 'country', ['region_guid'], ['guid'])
    op.drop_index(op.f('ix_autonomic_district_guid'), table_name='autonomic_district')
    op.drop_table('autonomic_district')
    # ### end Alembic commands ###
