"""change field local obj

Revision ID: a01ae887edf8
Revises: e2be5e2779ed
Create Date: 2023-01-09 17:42:26.151563

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision = 'a01ae887edf8'
down_revision = 'e2be5e2779ed'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('local_subject', sa.Column('people', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.drop_constraint('local_subject_urban_people_fkey', 'local_subject', type_='foreignkey')
    op.drop_constraint('local_subject_rural_people_fkey', 'local_subject', type_='foreignkey')
    op.create_foreign_key(None, 'local_subject', 'people', ['people'], ['guid'])
    op.drop_column('local_subject', 'rural_people')
    op.drop_column('local_subject', 'urban_people')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('local_subject', sa.Column('urban_people', postgresql.UUID(), autoincrement=False, nullable=True))
    op.add_column('local_subject', sa.Column('rural_people', postgresql.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'local_subject', type_='foreignkey')
    op.create_foreign_key('local_subject_rural_people_fkey', 'local_subject', 'people', ['rural_people'], ['guid'])
    op.create_foreign_key('local_subject_urban_people_fkey', 'local_subject', 'people', ['urban_people'], ['guid'])
    op.drop_column('local_subject', 'people')
    # ### end Alembic commands ###
