"""names

Revision ID: e2be5e2779ed
Revises: 1ca4517f40a5
Create Date: 2023-01-09 17:33:32.151689

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision = 'e2be5e2779ed'
down_revision = '1ca4517f40a5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('autonomic_district', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('country', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('federal_district', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('local_subject', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('local_subject', sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('region', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('region', 'name')
    op.drop_column('local_subject', 'type')
    op.drop_column('local_subject', 'name')
    op.drop_column('federal_district', 'name')
    op.drop_column('country', 'name')
    op.drop_column('autonomic_district', 'name')
    # ### end Alembic commands ###
